# Generated by Django 5.2 on 2025-05-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=12)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_id', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar', models.FileField(upload_to='media/images/')),
                ('pic', models.FileField(default='media/s1.png', upload_to='media/images/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
